# -*- coding: utf-8 -*-
"""mikayla_h_lab_01_python_intro.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/mikahamelin-gif/090c35c56d4bc8b1d740ad23a2216b26/lab_01_python_intro.ipynb

> ### Note on Labs and Assignments:
>
> Throughout this lab, you will see **🔧 Do the following** sections and a final 🔧 **Reflection** section
>
> ✅ You are expected to:
> - Complete each **"🔧 Do the following”** section by writing and running your own code or answering the prompted questions in a markdown or python cell below the section.
> - Answer the **Reflection** section at the end of the lab in your own words. This is your opportunity to summarize what you learned and connect the concepts.
>
> 🔧 Look for the **wrench emoji** 🔧 — it highlights where you're expected to take action!
>
> These sections are graded and are not optional.
>
> ---

# IS 4487 Lab 1 - Python Intro

## Outline

- Create and format cells in a notebook
- Create basic variables in Python
- Experiment with how to use AI to assist with a task.  

**NOTE ON USING AI:** Our goal is to have a healthy mentoring relationship with AI, not an unhealthy copy/paste relationship where AI dumps code and you accept it without hesitation.  Make sure to inspect and understand every line of code that you receive from AI.  If you don't understand a line, ask for an explanation!  

<a href="https://colab.research.google.com/github/Stan-Pugsley/is_4487_base/blob/main/Labs/lab_01_python_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

If you have any questions about Colab, you can read more here:  https://research.google.com/colaboratory/faq.html

## 🔧 Work with the Python Notebook

### 🔧 Task 1 - Do the following

Add a mathematical formula to add 15 and 22 in the cell below
"""

x = 15 + 22
print (x)

"""### 🔧 Task 2 - Do the following

Add a Markdown cell below this cell and write:

- A heading.
- Your major
- Your favorite food

# About Me
#### *Mikayla Hamelin*  
**Major:** Entrepreneurship  
**Favorite Food:** Salmon

### 🔧 Task 3 - Do the following

Create a variable called "x" with the value "Hello World".  Print the value of the variable
"""

x = 'hello world'
print (x)

"""### 🔧 Task 4 - Do the following

Try a task with the help of AI.  Ask Gemini to import the "art" library and create word art with the letters your name.  Add the code in the box below.
"""

!pip install art
import art
art.tprint("Mikayla")

"""### 🔧 Task 5: Reflection (100 words or less per question)

1. Describe your feelings as you wrote Python code?  Does this feel intimidating or fun?
2. What would be a good strategy in working with AI to ensure that you are driving the process and learning, as opposed to giving control to Gemini?

### ✍️ Your Response: 🔧
1.  I used to code a lot when I was in engineering, and it was a long time ago, but it feels good to get back into it. I am having a lot of fun rediscovering this. I forgot I installed the extensions to make the screen fun, like having cats on the top bar, and having combos and "power". I can't wait to remember even more and get back into the flow of things.
2. I think that making sure that I'm asking AI to do specific things, and reviewing the code after it's written, and practicing enough to be able to find errors means that I'm learning as well as using it as a good tool.

## Export Your Notebook to Submit in Canvas
- In the top menu, go to File > Download, click "Download .ipynb". Save the file to your laptop.
- In the left side menu, click the Folder icon, then click the "Upload to Session Storage" icon, and select the above saved file to add it to Colab's temporary Virtual Machine (VM) that allows us to work on our files in Colab.
- Convert the file to HTML using the code below.  You may be asked to approve access to the files
- Find the output file under Files in the left side menu
- Download your HTML file (*lab_01_python_intro.html*) as your completed lab, to be uploaded to Canvas
"""

!jupyter nbconvert --to html "mikayla_h_lab_01_python_intro (1).ipynb"

"""## Submit your assignment

- Make sure that all of your output is shown.  If you get the “unable to render code block” error, try refreshing the cache or downloading raw data to manually upload into Colab as a workaround.
- Upload your HTML file to Canvas
- Optionally, save your file in your own GitHub account for future use

"""